repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.8

- repo: https://github.com/PyCQA/pylint
  rev: v2.14.1
  hooks:
    - id: pylint
      args:
        - --disable=unused-argument

- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
    - id: autoflake
      args:
        - --in-place
        - --remove-unused-variables            
        - --remove-all-unused-imports